### ISSUE TITLE
8FACE smooth transition between scenes

### ISSUE THREAD

**Issue by feralseed** [stoermelder/vcvrack-packone#145]
Hello badass programmer.
I don't know if this is possible... 
Setting the transition speed from one scene to the next would be amazing. Thanks.

**Comment by vcvrackideas** [comment]
I just made it with 8face - polycon - polyslewlimiter and then CV map if you're curious. AFAIK Ben said sometime that it wouldn't be possible inside the 8face module itself just because it run a static switching algorithm between saved presets in Ram. But my way works pretty well. I will upload a detail tutorial tomorrow on it. Cheers!

**Comment by stoermelder** [comment]
8FACE is basically a preset switcher. As every developer defines by himself how a preset for a module is structured and which data is contained I can't look inside it. Just imagine, how should a transition of a sampler module work, when the module only stores the filename inside the preset?
However, it is possible smoothly change all the parameters of a module. It is done by "Morph" of 23volts and soon will be available in TRANSIT #146 similar to 8FACE.
