### ISSUE TITLE
STRIP - Thought: take you to Library for unresolved Slugs

### ISSUE THREAD

**Issue by baconpaul** [stoermelder/vcvrack-packone#18]
Strip is super clever. Thank you for writing it. 

I was thinking: if someone gives me a strip which uses a plugin I don’t have in my library (or if I give people a strip which uses a library they don’t have) right now you just kinda skip that module gracefully.  But in your moduleFromJson code you do return NULL if you can’t load the plugin and at that point you know the slug name.

Have you considered doing something like: for a strip have a “plugins needed” mode which scans the strip, looks for unresolved slugs, and perhaps even pops up a temp web page with links to library to search for those slugs (that is, if BaconMusic is missing - generally a smart choice of course - and someone shares a strip that references it you guide them to https://vcvrack.com/plugins.html#BaconMusic). 

Sort of like when someone sends you a .deb file and you can resolve the dependencies; or when you are in a pip3 python env and you can grab the versions you need, strip has enough info to guide the download/restart cycle I think. (Heck, depending on how the library URLs are implemented, you may even be able to go register for folks but I know that API is shifting still).

**Comment by stoermelder** [comment]
Hi Paul,
right now a very similiar popup comes up as when opening a patch with missing plugins. It tells you which module from which slug is missing.
I'm not sure if it's a good idea to do "my own thing" here. I'd rather jump on what Rack is doing in the future when modules are missing in patches instead of inventing something right now.
Thinking about it, I got an idea: I could add a dummy blank in the space where the module is missing, with some text and a link-button on the panel...

**Comment by baconpaul** [comment]
Yeah that’s a way better idea

**Comment by stoermelder** [comment]
Added availibility-check to STRIP and STRIP++ as implemented in Rack v2.5.0.

**Comment by baconpaul** [comment]
wow blast from the past! Thanks!
