### ISSUE TITLE
TRANSIT - add phase input

### ISSUE THREAD

**Issue by stoermelder** [stoermelder/vcvrack-packone#182]

**Comment by xandramax** [comment]
[This patch](https://github.com/stoermelder/vcvrack-packone/files/5647888/TransitCrash.txt) crashes Rack on my end, as soon as Transit is right-clicked and the Port CV mode is changed from "Trigger forward" to "Scan".

Oddly, Rack's log appears as if no crash happened.

**Comment by stoermelder** [comment]
Thanks, I missed that, fixed in c886e0574fd3ee526afa817e5d025d00e19b649b...

**Comment by xandramax** [comment]
I'm seeing behavior where when Port CV mode is set to Scan, and the Port CV input is not connected, clicking on snapshots to load them in Read mode no longer works. Also, in this case shift-click to load in Write mode doesn't work either. Snapshot loading works as expected as long as Port CV mode is not set to Scan.

I understand Port Scan CV should override manual shapshot loading, but the port should probably be ignored if it isn't connected. 

For write mode, maybe Scan CV could be temporarily ignored in order to allow for editing without disconnecting the CV or changing the Port CV mode? Algomorph behaves something like this, freezing the visual state in edit mode, though clearly in the case of Transit it isn't possible to separate the audio from the visual (in terms of the state of mapped parameters).

For Read mode, another possible direction would be to have the Scan CV and manual selection act together in an additive way. Manually selecting a snapshot would then act like an offset, changing which snapshot corresponds to 0V at the Scan CV input. Again this is similar to the way Algomorph works. but maybe it doesn't fit as well here.

In any case, I'm really enjoying this enhancement. In the beta 3 branch for Algomorph, I've added a Phase output. This way, other modules can track Algomorph's phase even when multiple morph CV inputs are wrapping things around past the edges (another new feature: no internal limit on morph amount). Now together with Transit, the operators themselves can easily morph in lock-step with the algorithm morphing. Really cool!

Here's a [demo patch](https://github.com/stoermelder/vcvrack-packone/files/5648829/Transit-AlgomorphB3-FMOP-2.txt). It requires [Algomorph Beta 3](https://github.com/anlexmatos/FM-Delexander/releases/tag/Beta-3).

**Comment by stoermelder** [comment]
> I'm seeing behavior where when Port CV mode is set to Scan, and the Port CV input is not connected, clicking on snapshots to load them in Read mode no longer works. Also, in this case shift-click to load in Write mode doesn't work either. Snapshot loading works as expected as long as Port CV mode is not set to Scan.
> 
> I understand Port Scan CV should override manual shapshot loading, but the port should probably be ignored if it isn't connected.

Yes, good point, I modified it behaving this way a few moments ago.
I will check and respond to the other suggestions later.

**Comment by stoermelder** [comment]
I'm closing this issue and will pursue any further enhancements in a new issue (which will be considered in a future update).
