### ISSUE TITLE
Strip - input output mapping through dummies

### ISSUE THREAD

**Issue by baconpaul** [stoermelder/vcvrack-packone#20]
One more idea. And again I don’t mind if you reject and close these of course. And this is the last one!

Strip is basically making a sub program in rack. In most modern languages subprograms have input and output parameters. In strip this would be expressed as unbound inputs and outputs in the generated modules 

But - and work with me here - imagine if strip or another module in your family was basically a bunch of labeled echoes. So when I set up strip I also get 10 input output pairs with a user editable label where output is input. 

This would be useful because that would be the place in my strip where I intend you to patch 

So imagine I have a strip which goes from poly midi to audio. Right now you have to put the 1v/oct gate and vel somewhere inside the newly added modules and get the audio from somewhere in the graph 

If strip-wide had a bunch of slots I could wire the output of 3 slots to my midi ins and the output of my vca back into strip for the outs. And make nice labels on them. Then when you open a strip you kinda know the points to connect to and they are documented with names if you want default behavior 

Of course you can always repatch. But if you had advertised patch points you kinda start to move towards the max/msp subpatch idea. 

Does this make sense?

**Comment by stoermelder** [comment]
Hi Pual, yes makes sense to me. Sounds like a interesting idea. Have you another module in mind that provides these patchpoints? I looked trough Rack's module browser and found nothing actually that could be used as patchpoints in a meaningful way…

**Comment by baconpaul** [comment]
No I didn’t. I thought about writing one (I mean it is not a *hard* module  write) so i could do this but thought instead perhaps you would like to bundle it with strip. 

I could also imagine the Strip module having two widgets for itself; one the narrow strip you have now and the other wider with the patch points in it then just put this functionality into the strip module itself.

(What I’m really thinking is “strip is so close to ‘foldable module set’ which is really what the max/map patches are” and so part of me thinks you want these patch points available on the strip module itself so you can even consider hiding or compacting the other modules in a future iteration ... but that’s just me thinking out loud).

**Comment by stoermelder** [comment]
I think it's better to do a separate module. First, you can scale how many patchpoints you want, just add another patchpoint-module. Second, I can image that someone wants to have "inputs" as the most left module and "outputs" on the most right module, when building an effect. Or at some significant position in the middle the strip.
Thinking one step further, some sort of macro-knobs could be useful too...

**Comment by baconpaul** [comment]
yeah right - like what's the control surface for your patch basically. So inputs have a knob and an input which echos; and outputs are echo only or maybe e echo and a gain.

**Comment by stoermelder** [comment]
A quick sketch, nothing finished yet...
![Anmerkung 2019-07-09 235550](https://user-images.githubusercontent.com/47640667/60925887-32608280-a2a5-11e9-8e94-72fd48596e84.jpg)

**Comment by mattcollier** [comment]
Hello, STRIP rocks!  What we're looking for is the equivalent of an 'instrument rack' in Ableton Live. What is need is a convenient way of patching the instrument rack into the rest of the rack which is what this issue is about.  But also, what is needed is a convenient way to provide modulation to the internals.  This is 'mapping' in Ableton as demonstrated here: https://youtu.be/wqgG9rBrRcs?t=268

So, just like we need a patch panel for inputs and outputs, we need a generic set of knobs and CV jacks that can be mapped to CV that is internal to the instrument rack.  Something like knobs from vult: https://modlfo.github.io/VultModules/knobs/

I think being able to label the knobs in a meaningful way is a pretty critical feature.

**Comment by stoermelder** [comment]
This has come a very long way but finally a simple module for this purpose is available. It keeps connection in from out a strip intact when using "Load with replace". It is quite similar to the technique demonstrated by @vcvrackideas in one of his recent tutorials but with cables instead of teleportation.
https://www.youtube.com/watch?v=YeCT7rOq70Y

**Comment by vcvrackideas** [comment]
Nice Ben and thanks for the mention. However can't get an idea on how to use it, may I ask you provide any kind of GIF or just picture?

**Comment by stoermelder** [comment]
The module wasn't working at all before, sorry for that :-( And there is a bug somewhere causing missing cables I need to search for. Still, I did a short clip for demonstration.
https://youtu.be/xGKoQdN9K60

**Comment by stoermelder** [comment]
I'm closing this for now. Future feature requests go into new issues.
