### ISSUE TITLE
HISTORY

### ISSUE THREAD

**Issue by stoermelder** [stoermelder/vcvrack-packone#24]
New module. Just as reminder, more details will follow later.

**Comment by stoermelder** [comment]
Module for storing Rack's undo-history within a patch. 
Currently not possible: There is no way to serialize custom undo actions implemented by modules.
https://github.com/VCVRack/Rack/issues/1638

**Comment by david-c14** [comment]
I'm going to comment here, rather than on the VCVRack/Rack github.

Surely this can only work if you can somehow force every developer to revisit their custom `history::Action`s to implement the serialize/deserialize methods.

Also I wasn't clear what your intention was for the slug. I myself have implemented only one custom `history::Action` class, but it uses lambda functions to implement undo and redo.  So that one custom class is used to undo about 20 different things, each instance potentially having different behaviour. I'd have to choose the appropriate slug for each instance (which I could do: I'm just pointing out that it would potentially color exactly how you intended to implement the slugs)

**Comment by stoermelder** [comment]
I missed the necessity of slugs at first. The problem is obviously deserializing JSON to instances of some identified class, exactly how you described the situation. Rack uses slugs for plugins and modules, the same concept would be needed for `history::Action`.
Still, this proposal must be considered at least :-)

**Comment by stoermelder** [comment]
Closing this for now. Rack's API does not provide the necessary functions for creating a serializable undo-history. This might change in the future, but it is impossible with Rack v2.
