### ISSUE TITLE
Transit and 8Face don't work with Stellare Modular

### ISSUE THREAD

**Issue by rasavell** [stoermelder/vcvrack-packone#336]
Just a heads up. Probably Stellare's problem.

**Comment by stoermelder** [comment]
Can I ask you to be a bit more specific? 
I tried Stellare Modular Pelisia and can't see anything wrong?

**Comment by rasavell** [comment]
I will try them again to double check.

**Comment by rasavell** [comment]
Yes, Pelisia looks all good. I noticed when testing the sequencers - Nomlia, Azular, Andromeda, and also the switches AL14,AL18 etc. 
that Transit doesn’t catch the selector buttons, but it does handle all the dials etc.  8Face MKII handles everything, no problem, I think.

I’ve noticed similar behavior with some other modules like docB GenScale. Let me know if you’d like me to test further.

Also, f you have a moment could you clarify something for me? What’s the difference in the methods (Snapshot vs Preset? Storage locations I presume. Preset is using the VCV system maybe? ). And are there advantages to using one method over the other. 

Damn these are awesome modules. I’m sure you hear that a lot. But adding my two thumbs up.

Rob

**Comment by stoermelder** [comment]
I did explain the differences here some time ago, I hope it clears things up:
https://community.vcvrack.com/t/stoermelder-8face-mk2-vs-transit/15335/5

**Comment by stoermelder** [comment]
The problem with the buttons is that they are not representing the current internal state but the current state of the button - it is 1 when pressed and 0 otherwise. The internal state toggles between 0 and 1 on each button press. TRANSIT can nothing do about that as it has no knowledge about the internal state, just the current state of the button.

That been said TRANSIT does handle buttons not very well in general - it makes little sense to morph between different button states as they usually have only values 0 and 1.
