### ISSUE TITLE
Audio 64 - multi devices?

### ISSUE THREAD

**Issue by Eurikon** [stoermelder/vcvrack-packone#49]
Hi Ben just a thougth.
Is it technically possible to create 2 device windows in the module, that will allow to select any of the audio devices found on the machine. 
And then let the user assign those devices to any of the unassigned connections. 
Or in groups, say if device one offers 16 channels, the module then will automatically occupy the first 16 connections, leaving the others unassigned for the second device.

It should also prohibit to select the same device twice.

**Comment by Eurikon** [comment]
I just realize that VCV can only use one audio device at a time even if 2 were available in it. 
Since it audio engine uses one device to sync to it, or something like that right?

**Comment by stoermelder** [comment]
Hi Latif,
to be honest, I didn't dig that deep in Rack's Audio engine yet. I guess you might be right, but I don't know how Rack's engine syncs to the interface excatly.
I added Audio-64 just because I wanted to use it myself and because it was a really easy task (just needed to change the number of ports and creating a panel).

**Comment by stoermelder** [comment]
I'm closing this because Rack v2 will support it.
https://community.vcvrack.com/t/rack-development-blog/5864/45
